spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DB_URL}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}

auth:
  jwt:
    secret: ${JWT_SECRET}

notification:
  internal:
    secret: ${NOTIFICATION_INTERNAL_SECRET}
